In [42]:
import pandas as pd
import numpy as np
from sklearn import linear_model 


In [43]:
df= pd.read_excel('C:\\Users\\aivin.joy\\OneDrive - Experion Technologies (India) Pvt. Ltd\\Personal\\Data Science\\houseprice2.xlsx')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [44]:
df.bedrooms.median()

4.0

In [45]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())

In [46]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [47]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [48]:
reg.predict([[3000,4,15]])

C:\Users\aivin.joy\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([602590.07937407])

In [49]:
reg.predict([[3000,3,5]])

C:\Users\aivin.joy\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([611518.37838246])

Sample 2
Salary Prediction

In [50]:
df2= pd.read_excel('C:\\Users\\aivin.joy\\OneDrive - Experion Technologies (India) Pvt. Ltd\\Personal\\Data Science\\hiring.xlsx')
df2

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [53]:
df2.experience=df2.experience.fillna("zero")
df2

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [54]:
df2.test_score=df2.test_score.fillna(df2.test_score.median())
df2

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [22]:
! pip install word2number

In [23]:
! pip install num2words

In [24]:
from word2number import w2n

In [55]:
df2.experience=df2.experience.apply(w2n.word_to_num)
df2

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [57]:
reg = linear_model.LinearRegression()
reg.fit(df2[['experience','test_score','interview_score']],df2['salary'])

LinearRegression()

In [58]:
reg.predict([[2,9,6]])

C:\Users\aivin.joy\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [59]:
reg.predict([[12,10,10]])

C:\Users\aivin.joy\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])